apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            #- name: MYSQL_DATABASE
            #  value: wordpress
            - name: MYSQL_ROOT_PASSWORD  
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: password
            #- name: MYSQL_DATABASE # 구성할 database명
            #  value: k8sdb
            #- name: MYSQL_USER # database에 권한이 있는 user
            #  value: k8suser
            #- name: MYSQL_ROOT_HOST # 접근 호스트
            #  value: '%'  
            #- name: MYSQL_PASSWORD 
            #  valueFrom:
            #   secretKeyRef:
            #      name: mysql-user-password
            #      key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: gp2-pvc-1
